# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'valhalla/gui/ValhallaExtraParamsDialogUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ValhallaExtraParams(object):
    def setupUi(self, ValhallaExtraParams):
        ValhallaExtraParams.setObjectName("ValhallaExtraParams")
        ValhallaExtraParams.resize(327, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(ValhallaExtraParams)
        self.verticalLayout.setObjectName("verticalLayout")
        self.extra_params_text = QtWidgets.QTextEdit(ValhallaExtraParams)
        self.extra_params_text.setTabChangesFocus(True)
        self.extra_params_text.setObjectName("extra_params_text")
        self.verticalLayout.addWidget(self.extra_params_text)
        self.buttonBox = QtWidgets.QDialogButtonBox(ValhallaExtraParams)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ValhallaExtraParams)
        self.buttonBox.accepted.connect(ValhallaExtraParams.accept) # type: ignore
        self.buttonBox.rejected.connect(ValhallaExtraParams.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ValhallaExtraParams)

    def retranslateUi(self, ValhallaExtraParams):
        _translate = QtCore.QCoreApplication.translate
        ValhallaExtraParams.setWindowTitle(_translate("ValhallaExtraParams", "Extra request parameters"))
        self.extra_params_text.setPlaceholderText(_translate("ValhallaExtraParams", "{}"))
